app = "anniexboda-ma1e5q"
primary_region = "iad"

[processes]
  # هنا التغيير: خلينا الأمر يشغل ملف الرونر مباشرة
  app = "python3 runner.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
