name: Sync to Hugging Face
on:
  push:
    branches: [Master]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "boda@example.com"
          git config --global user.name "boda058961"
          # إضافة رابط الهجينج فيس
          git remote add hf https://boda058961:$HF_TOKEN@huggingface.co/spaces/boda058961/Music
          # رفع الملفات من Master لـ main غصب
          git push --force hf Master:main
